### PR TITLE
Add a few missing words

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by kdrag0n — CHANGES_REQUESTED** [review]
Thanks, you're definitely right about the missing "install". I'm not sure about replacing "in" with "as" though; the idea is to install Google Play Services inside a secondary user profile.

**Comment by ghost** [comment]
Would a user know how to install it "in" the profile vs installing it "as" a secondary user?

**Comment by kdrag0n** [comment]
I think "in" makes more sense because people generally refer to content as being "in" profiles.

**Comment by kdrag0n** [comment]
Looks good, thanks!

**Pull request merged**
